datasource:
  username: ${DATABASE_USERNAME}
  password: ${DATABASE_PASSWORD}
  driver-class-name: org.mariadb.jdbc.Driver
  url: jdbc:mariadb://database-1.cvyclyh4jg14.ap-northeast-2.rds.amazonaws.com:3306/shopping_mall_project

dependencies:
  kakao_flutter_sdk_user: ^1.8.0 # 카카오 로그인

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jwtpassword:
  source: ${JWT_CODE}
