datasource:
  username: ${DATABASE_USERNAME}
  password: ${DATABASE_PASSWORD}
  driver-class-name: org.mariadb.jdbc.Driver
  url: jdbc:mariadb://database-1.cvyclyh4jg14.ap-northeast-2.rds.amazonaws.com:3306/shopping_mall_project


jwtpassword:
  source: ${JWT_CODE}

kakao:
  grant_type: authorization_code
  client.id: fbe429887ccaa8b1ee741eaedb0fad31
  client.secret: 3SjTZhmIIm0Hon085OdufmyKrYBqf19N
  redirect.url: http://localhost:8080/oauth/kakao/callback
  request.url: https://kauth.kakao.com/oauth/token
  user_me.url: https://kapi.kakao.com/v2/user/me